"""make_heartbeat_worker_id_unique

Revision ID: dac0f4bb02eb
Revises: 001_initial
Create Date: 2026-07-03 20:59:30.470863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac0f4bb02eb'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobs_idempotency_key_key'), 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint('uq_worker_heartbeats_worker_id', 'worker_heartbeats', ['worker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_worker_heartbeats_worker_id', 'worker_heartbeats', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('jobs_idempotency_key_key'), 'jobs', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
